### PR TITLE
Fixing detection parsing bug and polling a single detection

### PR DESCRIPTION
**Pull request by matthastings**

### CODE REVIEW

**Comment by matthastings** [comment]
@aztechian tried adding you as a reviewer but can't find your username. Do you mind reviewing this PR and/or any ideas why I can't add you?

**Comment by aztechian** [comment]
I think because I'm not a contributor on this repo, and I haven't explicitly been given permissions.
This got to me though, so there's that ;)

looking now...

**Review by aztechian — APPROVED** [review]
LGTM.

I was contemplating whether it would be any better to store `detection.attributes` separately in the Detection constructor? It would only really simplify the calls to get(), ie
```python
return self._attributes.get('last_remediated_status', dict({"remediation_state": "Not remediated"}))
```
mostly just for reducing code duplication.

**Comment by matthastings** [comment]
@aztechian thanks for the review. Added the attributes property to make the calls less repetitive

**Review by aztechian — APPROVED** [review]

**Pull request merged**
